# Generated by Django 5.0.6 on 2024-07-02 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("tmdb_id", models.IntegerField(primary_key=True, serialize=False)),
                ("imdb_id", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=100)),
                ("gender", models.IntegerField()),
                ("birthday", models.DateTimeField()),
                ("movie_credits", models.CharField()),
                ("picture", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "imdb_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=150)),
                ("release_date", models.DateTimeField()),
                ("genre", models.CharField()),
                ("plot", models.TextField()),
                ("plot_words", models.TextField()),
                ("keyword_list", models.TextField()),
                ("worldwide_gross", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_tmdb_id", models.CharField(max_length=15)),
                ("film_title", models.CharField(max_length=150)),
                ("actor_name", models.CharField(max_length=50)),
                ("lead", models.IntegerField()),
                (
                    "film_imdb_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="film_creator.film",
                    ),
                ),
            ],
        ),
    ]
