# Generated by Django 5.0.6 on 2024-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film_creator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
