# Generated by Django 5.0.6 on 2024-07-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film_creator", "0002_alter_actor_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="worldwide_gross",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
