# Generated by Django 5.0.6 on 2024-07-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film_creator", "0003_alter_actor_birthday_alter_film_worldwide_gross"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="release_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="film",
            name="worldwide_gross",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
