# Generated by Django 5.0.6 on 2024-07-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film_creator", "0004_alter_film_release_date_alter_film_worldwide_gross"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="actor_tmdb_id",
        ),
        migrations.RemoveField(
            model_name="role",
            name="film_imdb_id",
        ),
        migrations.AddField(
            model_name="role",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="film_creator.actor",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="film",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actor_roles",
                to="film_creator.film",
            ),
        ),
    ]
